### ISSUE TITLE
Document the possibility to use scope "provided"

### ISSUE THREAD

**Issue by fanf** [mrvisser/sealerate#14]
Hello, 

I love sealerate: does one thing really nicelly!
Unfortunatly, it has a dependency toward scala-compiler, and if we don't notice, it adds around 12Mo to any war/fat jar using sealerate. 

But as sealerate is a pure compile-time macro, it can be used with the maven scope "provided". 
That possibility should be documented (not sure about the sbt syntax but I guess it is:

```
libraryDependencies += "ca.mrvisser" %% "sealerate" % "0.0.5" % "provided"
```

**Comment by Philippus** [comment]
would my PR fix this?
