### ISSUE TITLE
Warning improvement

### ISSUE THREAD

**Issue by jeantil** [mrvisser/sealerate#2]
Hello, 

it would be nice to change the wording of the "empty children" warning to explain that when called in the module where the cases are defined, the macro call should be placed at the end. 

```
sealed trait SealedTraitObjectsOnly

object SealedTraitObjectsOnly {
  def all = values[SealedTraitObjectsOnly] 
  case object Item1 extends SealedTraitObjectsOnly
  case object Item2 extends SealedTraitObjectsOnly
}
```

outputs the warning

```
sealed trait SealedTraitObjectsOnly

object SealedTraitObjectsOnly {
  case object Item1 extends SealedTraitObjectsOnly
  case object Item2 extends SealedTraitObjectsOnly
  def all = values[SealedTraitObjectsOnly] 
}
```

doesn't :)

**Comment by mrvisser** [comment]
Good catch, thanks for filing an issue. I've fixed this in https://github.com/mrvisser/sealerate/pull/6
